# Generated by Django 5.0.2 on 2024-02-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_user_group',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='product',
            name='min_user_group',
            field=models.IntegerField(default=5),
        ),
    ]
